[package]
authors = ["Antoni Boucher <antoni.boucher@adgear.com>"]
name = "ftp1"
version = "0.1.0"
[dependencies]
bytes = "^0.4.5"
tokio-core = "^0.1.10"
tokio-io = "^0.1.3"

[dependencies.futures-await]
git = "https://github.com/alexcrichton/futures-await"
